# array manipulation

In [2]:
import numpy as np
a = np.arange(9)

print(a)

b = a.reshape(3,3)
b

[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#numpy arithmetic operation

In [3]:
a = np.arange(12).reshape(4,3)

In [4]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [5]:
b = np.array([[10,11,12]])
b

array([[10, 11, 12]])

In [6]:
np.add(a,b)

array([[10, 12, 14],
       [13, 15, 17],
       [16, 18, 20],
       [19, 21, 23]])

In [7]:
np.substract(a,b)

AttributeError: module 'numpy' has no attribute 'substract'

In [ ]:
np.subtract(a,b)

In [ ]:
np.multiply(a,b)

In [ ]:
np.divide(a,b)

In [8]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [9]:
a[4:]

array([4, 5, 6, 7, 8])

In [10]:
a = a.reshape(3,3)

In [11]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
a = np.array([[1,2,3], [1,2,3]])
a

array([[1, 2, 3],
       [1, 2, 3]])

In [18]:
b = np.array([[4,5,6],[7,8,9]])
b

array([[4, 5, 6],
       [7, 8, 9]])

In [22]:
np.concatenate((a,b), axis=0)

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
np.concatenate((a,b), axis=1)

array([[1, 2, 3, 4, 5, 6],
       [1, 2, 3, 7, 8, 9]])

In [33]:
a.shape

(2, 2)